version: "3.7"

networks:
  test:
    name: fabric_test
services:
  orderer1.example.com:
    container_name: orderer1.example.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer1.example.com:9443
    working_dir: /root
    command: orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - test
    volumes:
      - /home/huy/TTTN/FoodSupplyChain/network/Orderer/Orderer1/msp:/var/hyperledger/orderer/msp
      - /home/huy/TTTN/FoodSupplyChain/network/Orderer/Orderer1/tls:/var/hyperledger/orderer/tls

  orderer2.example.com:
    container_name: orderer2.example.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.example.com:9444
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:8053
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    working_dir: /root
    command: orderer
    ports:
      - 8050:8050
      - 8053:8053
      - 9444:9444
    networks:
      - test
    volumes:
      - /home/huy/TTTN/FoodSupplyChain/network/Orderer/Orderer2/msp:/var/hyperledger/orderer/msp
      - /home/huy/TTTN/FoodSupplyChain/network/Orderer/Orderer2/tls:/var/hyperledger/orderer/tls

  orderer3.example.com:
    container_name: orderer3.example.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer3.example.com:9445
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9053
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-6054-ca-orderer.pem]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 9050:9050
      - 9053:9053
      - 9445:9445
    networks:
      - test
    volumes:
      - /home/huy/TTTN/FoodSupplyChain/network/Orderer/Orderer3/msp:/var/hyperledger/orderer/msp
      - /home/huy/TTTN/FoodSupplyChain/network/Orderer/Orderer3/tls:/var/hyperledger/orderer/tls

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - test

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    networks:
      - test

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7984:5984
    networks:
      - test

  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 8984:5984
    networks:
      - test

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 9984:5984
    networks:
      - test

  peer0.producer.example.com:
    container_name: peer0.producer.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ID=peer0.producer.example.com
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_ADDRESS=peer0.producer.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.producer.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.example.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/tlscacerts/tls-localhost-7054-ca-producer.pem
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_LOCALMSPID=ProducerMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_OPERATIONS_LISTENADDRESS=peer0.producer.example.com:8444

    depends_on:
      - couchdb1
    working_dir: /root
    ports:
      - 7051:7051
      - 8444:8444
    command: sh -c "apt-get update && apt-get install -y jq && peer node start"
    volumes:
      - /home/huy/TTTN/FoodSupplyChain/network/Producer/Peer/msp:/etc/hyperledger/crypto/peer/msp
      - /home/huy/TTTN/FoodSupplyChain/network/Producer/Peer/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - /home/huy/TTTN/FoodSupplyChain/network/chaincode:/chaincode
      - /home/huy/TTTN/FoodSupplyChain/network/config/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - test

  peer0.processor.example.com:
    container_name: peer0.processor.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ID=peer0.processor.example.com
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_ADDRESS=peer0.processor.example.com:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.processor.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.processor.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.processor.example.com:8051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/tlscacerts/tls-localhost-8054-ca-processor.pem
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_LOCALMSPID=ProcessorMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=peer0.processor.example.com:8445

    depends_on:
      - couchdb2
    ports:
      - 8051:8051
      - 8445:8445
    working_dir: /root
    command: sh -c "apt-get update && apt-get install -y jq && peer node start"
    volumes:
      - /home/huy/TTTN/FoodSupplyChain/network/Processor/Peer/msp:/etc/hyperledger/crypto/peer/msp
      - /home/huy/TTTN/FoodSupplyChain/network/Processor/Peer/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - /home/huy/TTTN/FoodSupplyChain/network/chaincode:/chaincode
      - /home/huy/TTTN/FoodSupplyChain/network/config/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - test

  peer0.distributor.example.com:
    container_name: peer0.distributor.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ID=peer0.distributor.example.com
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_ADDRESS=peer0.distributor.example.com:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.distributor.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.example.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.example.com:9051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/tlscacerts/tls-localhost-9054-ca-distributor.pem
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_LOCALMSPID=DistributorMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=peer0.distributor.example.com:8446

    depends_on:
      - couchdb3
    working_dir: /root
    command: sh -c "apt-get update && apt-get install -y jq && peer node start"
    ports:
      - 9051:9051
      - 8446:8446
    volumes:
      - /home/huy/TTTN/FoodSupplyChain/network/Distributor/Peer/msp:/etc/hyperledger/crypto/peer/msp
      - /home/huy/TTTN/FoodSupplyChain/network/Distributor/Peer/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - /home/huy/TTTN/FoodSupplyChain/network/chaincode:/chaincode
      - /home/huy/TTTN/FoodSupplyChain/network/config/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - test

  peer0.intermediate.example.com:
    container_name: peer0.intermediate.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ID=peer0.intermediate.example.com
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_ADDRESS=peer0.intermediate.example.com:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.intermediate.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.intermediate.example.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.intermediate.example.com:10051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/tlscacerts/tls-localhost-10054-ca-intermediate.pem
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_LOCALMSPID=IntermediateMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=peer0.intermediate.example.com:8447

    depends_on:
      - couchdb4
    working_dir: /root
    command: sh -c "apt-get update && apt-get install -y jq && peer node start"
    ports:
      - 10051:10051
      - 8447:8447
    volumes:
      - /home/huy/TTTN/FoodSupplyChain/network/Intermediate/Peer/msp:/etc/hyperledger/crypto/peer/msp
      - /home/huy/TTTN/FoodSupplyChain/network/Intermediate/Peer/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - /home/huy/TTTN/FoodSupplyChain/network/chaincode:/chaincode
      - /home/huy/TTTN/FoodSupplyChain/network/config/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - test

  peer0.consumer.example.com:
    container_name: peer0.consumer.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - CORE_PEER_ID=peer0.consumer.example.com
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_ADDRESS=peer0.consumer.example.com:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.consumer.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.example.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.example.com:11051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/tlscacerts/tls-localhost-11054-ca-consumer.pem
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_LOCALMSPID=ConsumerMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=peer0.consumer.example.com:8448

    depends_on:
      - couchdb5
    working_dir: /root
    command: sh -c "apt-get update && apt-get install -y jq && peer node start"
    ports:
      - 11051:11051
      - 8448:8448
    volumes:
      - /home/huy/TTTN/FoodSupplyChain/network/Consumer/Peer/msp:/etc/hyperledger/crypto/peer/msp
      - /home/huy/TTTN/FoodSupplyChain/network/Consumer/Peer/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - /home/huy/TTTN/FoodSupplyChain/network/chaincode:/chaincode
      - /home/huy/TTTN/FoodSupplyChain/network/config/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - test
